__author__ = 'wcong'

'''
how tow node communicate
communicate type
'''
REQUEST_SEND_REQUEST = '001'
REQUEST_GET_STATUS = '002'
REQUEST_SEND_RESULT = '003'
REQUEST_INIT_ENGINE = '004'
REQUEST_IS_SPIDER_IDLE = '005'
REQUEST_START_A_ENGINE = '006'
REQUEST_ADD_ME = '007'
REQUEST_STOP_ENGINE = '008'

RESPONSE_INIT_REQUEST = '101'
RESPONSE_SPIDER_IDLE_STATUS = '102'
RESPONSE_SEND_REQUEST = '103'
RESPONSE_RESULT_OF_REQUEST = '104'
RESPONSE_STOP_ENGINE = '105'
END_SIGN = 'tcp_end_sign'

LENGTH = len(REQUEST_SEND_REQUEST)
